---
abstract: 'Object Oriented time objects'
author:
  - 'Matt Sergeant'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.84, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Time-Piece
no_index:
  directory:
    - t
    - inc
requires:
  Exporter: 5.57
resources:
  repository: https://github.com/rjbs/Time-Piece
version: 1.25_01
